package FinalProject;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author brend
 */
public class UI_AddStudent extends javax.swing.JFrame {

    /**
     * Creates new form Grades
     */
    public UI_AddStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Add_Student_Label = new javax.swing.JLabel();
        Home_Button = new javax.swing.JButton();
        First_Name = new javax.swing.JTextField();
        First_Name_Label = new javax.swing.JLabel();
        Last_Name_Label = new javax.swing.JLabel();
        Last_Name = new javax.swing.JTextField();
        Class_Label = new javax.swing.JLabel();
        Class = new javax.swing.JTextField();
        Submit_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Add_Student_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Add_Student_Label.setText("Add Student");

        Home_Button.setText("Home");
        Home_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_ButtonActionPerformed(evt);
            }
        });

        First_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        First_Name.setToolTipText("");

        First_Name_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        First_Name_Label.setText("First Name:");

        Last_Name_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Last_Name_Label.setText("Last Name:");

        Last_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Class_Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Class_Label.setText("Class:");

        Class.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Submit_Button.setText("Submit");
        Submit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Add_Student_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Last_Name_Label, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(First_Name_Label))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(First_Name)
                                .addComponent(Last_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Class_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Submit_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Class, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Home_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Add_Student_Label)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(First_Name_Label)
                    .addComponent(First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Last_Name_Label)
                    .addComponent(Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Class_Label)
                    .addComponent(Class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Submit_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(Home_Button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_ButtonActionPerformed
        super.dispose();
        new UI_Home().setVisible(true);
    }//GEN-LAST:event_Home_ButtonActionPerformed

    private void Submit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_ButtonActionPerformed
        String studentName = First_Name.getText() + " " + Last_Name.getText();
        String studentClass = Class.getText();
        
        if (First_Name.getText().isEmpty() || Last_Name.getText().isEmpty() || Class.getText().isEmpty()) {
            HelpfulFunctions.showMessage("Empty field detected. Please fill out all necessary fields.");
        } else {
            ArrayList<Student> CurrentStudentList = CreateLatestStudentList();
            Student StudentSelected = null;
            Boolean Duplicate = false;
                
            for (int i = 0; i < CurrentStudentList.size(); i++) {
                if (CurrentStudentList.get(i).Name().equalsIgnoreCase(studentName) && CurrentStudentList.get(i).StudentClass().equalsIgnoreCase(studentClass)) {
                    HelpfulFunctions.showMessage("Duplicate student name and class detected. Please enter a different student name or class.");
                    Duplicate = true;
                }
            }
            
            
            if (Duplicate == false) {
                StudentSelected = new Student(studentName, studentClass);

                if (StudentSelected.AddStudent()) {
                    HelpfulFunctions.showMessage("Successfully created new student!");
                    super.dispose();
                    new UI_Home().setVisible(true);

                } else {
                    HelpfulFunctions.showMessage("An error has occured.");
                }
            }
        }
    }//GEN-LAST:event_Submit_ButtonActionPerformed

    ArrayList CreateLatestStudentList() {
        File studentDir = new File("C:\\FinalProject\\Students.csv");
        ArrayList<Student> studentList = new ArrayList<Student>();
        try {
            BufferedReader reader = new BufferedReader(new FileReader(studentDir));
            String line = "";
            while ((line = reader.readLine()) != null) {
                String[] result = line.split(",");
                studentList.add(new Student(result[0], result[1]));
            }

            reader.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return studentList;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add_Student_Label;
    private javax.swing.JTextField Class;
    private javax.swing.JLabel Class_Label;
    private javax.swing.JTextField First_Name;
    private javax.swing.JLabel First_Name_Label;
    private javax.swing.JButton Home_Button;
    private javax.swing.JTextField Last_Name;
    private javax.swing.JLabel Last_Name_Label;
    private javax.swing.JButton Submit_Button;
    // End of variables declaration//GEN-END:variables
}
