package FinalProject;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author brend
 */
public class UI_EditStudentDetails extends javax.swing.JFrame {

    /**
     * Creates new form Grades
     */
    public UI_EditStudentDetails() {
        initComponents();
        UpdateChosenStudentFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Add_Student_Label = new javax.swing.JLabel();
        Home_Button = new javax.swing.JButton();
        Edited_First_Name = new javax.swing.JTextField();
        First_Name_Label = new javax.swing.JLabel();
        Last_Name_Label = new javax.swing.JLabel();
        Edited_Last_Name = new javax.swing.JTextField();
        Class_Label = new javax.swing.JLabel();
        Edited_Class = new javax.swing.JTextField();
        Submit_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Add_Student_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Add_Student_Label.setText("Edit Student Info");

        Home_Button.setText("Home");
        Home_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_ButtonActionPerformed(evt);
            }
        });

        Edited_First_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Edited_First_Name.setToolTipText("");

        First_Name_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        First_Name_Label.setText("First Name:");

        Last_Name_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Last_Name_Label.setText("Last Name:");

        Edited_Last_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Class_Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Class_Label.setText("Class:");

        Edited_Class.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Submit_Button.setText("Submit");
        Submit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Add_Student_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Last_Name_Label, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(First_Name_Label))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Edited_First_Name)
                                .addComponent(Edited_Last_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Class_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Submit_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Edited_Class, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Home_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Add_Student_Label)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(First_Name_Label)
                    .addComponent(Edited_First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Last_Name_Label)
                    .addComponent(Edited_Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Class_Label)
                    .addComponent(Edited_Class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Submit_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(Home_Button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_ButtonActionPerformed
        super.dispose();
        new UI_Home().setVisible(true);
    }//GEN-LAST:event_Home_ButtonActionPerformed

    private void Submit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_ButtonActionPerformed

        //Grab New Information
        String studentName = Edited_First_Name.getText() + " " + Edited_Last_Name.getText();
        String studentClass = Edited_Class.getText();

        //Check for valid user input
        if (Edited_First_Name.getText().isEmpty() || Edited_Last_Name.getText().isEmpty() || Edited_Class.getText().isEmpty()) {
            HelpfulFunctions.showMessage("Empty Field Detected. Please Fill Out All Necessary Fields.");
        } else {

            Student newStudentInfo = new Student(studentName, studentClass);
            ArrayList<Student> studentList = CreateLatestStudentList();
            Student chosenStudent = GetChosenStudentInfo();
            Student currentStudent = null;

            //find user selected student and remove from the student list
            for (int i = 0; i < studentList.size(); i++) {
                if (studentList.get(i).Name().equals(chosenStudent.Name())) {
                    currentStudent = studentList.get(i);

                    //Recreate student file and remove user selected student from list
                    currentStudent.CreateStudentFile();
                    studentList.remove(i);
                }
            }

            //Add other non-selected students in list to newly created file
            for (int i = 0; i < studentList.size(); i++) {
                currentStudent = studentList.get(i);
                currentStudent.AddStudent();
            }

            //Add edited info to newly created file
            if (newStudentInfo.AddStudent()) {
                HelpfulFunctions.showMessage(chosenStudent.Name() + " has been edited.");
                super.dispose();
                new UI_Home().setVisible(true);
            }

        }
    }//GEN-LAST:event_Submit_ButtonActionPerformed

    void UpdateChosenStudentFields() {
        File studentDir = new File("C:\\FinalProject\\EditedStudent.csv");
        Student EditedStudent = null;
        try {
            BufferedReader reader = new BufferedReader(new FileReader(studentDir));
            String line = "";
            while ((line = reader.readLine()) != null) {
                String[] result = line.split(",");
                EditedStudent = (new Student(result[0], result[1]));
            }

            reader.close();
        } catch (IOException e) {

        }
        
        String Name = EditedStudent.Name();
        String Class = EditedStudent.StudentClass();
        String[] FullName = Name.split(" ");
        String FirstName = FullName[0];
        String LastName = FullName[1];
        
        Edited_First_Name.setText(FirstName);
        Edited_Last_Name.setText(LastName);
        Edited_Class.setText(Class);
        
    }
    
    Student GetChosenStudentInfo() {
        File editedStudentDir = new File("C:\\FinalProject\\EditedStudent.csv");
        Student EditedStudent = null;
        try {
            BufferedReader reader = new BufferedReader(new FileReader(editedStudentDir));
            String line = "";
            while ((line = reader.readLine()) != null) {
                String[] result = line.split(",");
                EditedStudent = (new Student(result[0], result[1]));
            }

            reader.close();
        } catch (IOException e) {

        }

        return EditedStudent;

    }

    ArrayList CreateLatestStudentList() {
        File studentDir = new File("C:\\FinalProject\\Students.csv");
        ArrayList<Student> studentList = new ArrayList<Student>();
        try {
            BufferedReader reader = new BufferedReader(new FileReader(studentDir));
            String line = "";
            while ((line = reader.readLine()) != null) {
                String[] result = line.split(",");
                studentList.add(new Student(result[0], result[1]));
            }

            reader.close();
        } catch (IOException e) {
            
        }
        return studentList;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add_Student_Label;
    private javax.swing.JLabel Class_Label;
    private javax.swing.JTextField Edited_Class;
    private javax.swing.JTextField Edited_First_Name;
    private javax.swing.JTextField Edited_Last_Name;
    private javax.swing.JLabel First_Name_Label;
    private javax.swing.JButton Home_Button;
    private javax.swing.JLabel Last_Name_Label;
    private javax.swing.JButton Submit_Button;
    // End of variables declaration//GEN-END:variables

}