package FinalProject;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author brend
 */
public class UI_EditStudent extends javax.swing.JFrame {

    /**
     * Creates new form Grades
     */
    public UI_EditStudent() {
        initComponents();
        UpdateSelectionBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Edit_Student_Label = new javax.swing.JLabel();
        Home_Button = new javax.swing.JButton();
        Student_Selection_Box = new javax.swing.JComboBox<>();
        SelectStudentLabel = new javax.swing.JLabel();
        Delete_Button = new javax.swing.JButton();
        Edit_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Edit_Student_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Edit_Student_Label.setText("Edit Student");

        Home_Button.setText("Home");
        Home_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_ButtonActionPerformed(evt);
            }
        });

        Student_Selection_Box.setPreferredSize(new java.awt.Dimension(72, 23));

        SelectStudentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelectStudentLabel.setText("Select Student:");

        Delete_Button.setText("Delete");
        Delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_ButtonActionPerformed(evt);
            }
        });

        Edit_Button.setText("Edit");
        Edit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Edit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Delete_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SelectStudentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Edit_Student_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Student_Selection_Box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(Home_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Edit_Student_Label)
                .addGap(28, 28, 28)
                .addComponent(SelectStudentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Student_Selection_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Edit_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Delete_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(Home_Button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_ButtonActionPerformed
        super.dispose();
        new UI_Home().setVisible(true);
    }//GEN-LAST:event_Home_ButtonActionPerformed

    private void Delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_ButtonActionPerformed
        
        String selectedStudent = (String) Student_Selection_Box.getSelectedItem();
        Student selectedStudentObject = null;

        if (selectedStudent == null) {
            HelpfulFunctions.showMessage("Please select a student to delete.");
        } else {
            ArrayList<Student> studentList = CreateLatestStudentList();

            for (int i = 0; i < studentList.size(); i++) {
                if (studentList.get(i).Name().equals(selectedStudent)) {
                    selectedStudentObject = studentList.get(i);
                    
                    //Recreate student file without adding the removed student
                    selectedStudentObject.CreateStudentFile();
                    studentList.remove(i);
                }
            }
            
            //Add other students in list to newly created file
            for (int i = 0; i < studentList.size(); i++) {
                selectedStudentObject = studentList.get(i);
                selectedStudentObject.AddStudent();
            }
            
            HelpfulFunctions.showMessage(selectedStudent + " has been deleted.");
            super.dispose();
            new UI_Home().setVisible(true);
            
        }
    }//GEN-LAST:event_Delete_ButtonActionPerformed

    private void Edit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_ButtonActionPerformed
        String selectedStudent = (String) Student_Selection_Box.getSelectedItem();
        Student selectedStudentObject = null;

        if (selectedStudent == null) {
            HelpfulFunctions.showMessage("Please select a student to edit.");
        } else {
            File StudentDir = new File("C:\\FinalProject\\Students.csv");
            ArrayList<Student> studentList = new ArrayList<>();
            try {
                BufferedReader reader = new BufferedReader(new FileReader(StudentDir));
                String line = "";
                boolean found = false;
                while (found == false) {
                    line = reader.readLine();
                    String[] result = line.split(",");
                    if (result[0].equals(selectedStudent)) {
                        studentList.add(new Student(result[0], result[1]));
                        found = true;
                    }
                }

                reader.close();
            } catch (IOException e) {

            }

            selectedStudentObject = studentList.get(0);

            //Write Selected Student To EditedStudent.CSV To Be Referenced By Next Screen
            if (selectedStudentObject.AddEditedStudent()) {
                super.dispose();
                new UI_EditStudentDetails().setVisible(true);
            } else {
                HelpfulFunctions.showMessage("An error has occured.");
            }
        }
    }//GEN-LAST:event_Edit_ButtonActionPerformed

    //Populate box with all students
    void UpdateSelectionBox() {

        File studentDir = new File("C:\\FinalProject\\Students.csv");
        try {
            BufferedReader reader = new BufferedReader(new FileReader(studentDir));
            String line = "";
            while ((line = reader.readLine()) != null) {
                String[] result = line.split(",");
                Student_Selection_Box.addItem(result[0]);
            }

            reader.close();
        } catch (IOException e) {

        }
    }
    
      ArrayList CreateLatestStudentList() {
        File studentDir = new File("C:\\FinalProject\\Students.csv");
        ArrayList<Student> studentList = new ArrayList<Student>();
        try {
            BufferedReader reader = new BufferedReader(new FileReader(studentDir));
            String line = "";
            while ((line = reader.readLine()) != null) {
                String[] result = line.split(",");
                studentList.add(new Student(result[0], result[1]));
            }

            reader.close();
        } catch (IOException e) {
            
        }
        return studentList;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete_Button;
    private javax.swing.JButton Edit_Button;
    private javax.swing.JLabel Edit_Student_Label;
    private javax.swing.JButton Home_Button;
    private javax.swing.JLabel SelectStudentLabel;
    private javax.swing.JComboBox<String> Student_Selection_Box;
    // End of variables declaration//GEN-END:variables
}

